### ISSUE TITLE
What are the checklist of items to look out for to ensure reproducibility of the model pipeline as much as possible?

### ISSUE THREAD

**Issue by WaiMarn** [aimakerspace/ai-practitioner-handbook#86]
**Section Outline**
- Overview of model reproducibility
- List of items to check to ensure reproducibility
    - Model tests ie. API calls, algorithmic correctness
    - Model version control
    - Integration tests
    - Proper logging

 
 
**Definition of Done**
- [x] Completed `<chapter-num>/<filename.md>`
- [x] Verified against [self-review checklist](https://github.com/aisingapore/ai-practitioner-handbook/blob/main/REVIEWING.md)
- [x] Added section to [table of contents](https://github.com/aisingapore/ai-practitioner-handbook/blob/main/_toc.yml)
- [x] Page builds and displays correctly on local machine
